# Generated by Django 5.1.15 on 2026-06-09 23:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名')),
                ('code', models.SlugField(help_text='导出时使用的稳定标识,如 "zh_calvin"', unique=True, verbose_name='代号')),
                ('language', models.CharField(choices=[('zh', '中文'), ('ko', '韩文'), ('en', '英文'), ('el', '希腊文'), ('he', '希伯来文')], max_length=10, verbose_name='语言')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用中')),
            ],
            options={
                'verbose_name': 'AI 模型',
                'verbose_name_plural': 'AI 模型',
                'ordering': ['language', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Theologian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='英文名')),
                ('tradition', models.CharField(max_length=50, verbose_name='神学传统')),
                ('suggested_tags', models.JSONField(blank=True, default=list, verbose_name='预设标签')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
            ],
            options={
                'verbose_name': '神学家/传统',
                'verbose_name_plural': '神学家/传统',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TranslationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_title', models.CharField(max_length=200, verbose_name='源标题')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '翻译组',
                'verbose_name_plural': '翻译组',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('source_type', models.CharField(choices=[('sermon_audio', '讲道音频'), ('sermon_video', '讲道视频'), ('sermon_text', '讲稿文字'), ('commentary', '学术注释'), ('book', '神学著作'), ('url', 'URL抓取')], max_length=20, verbose_name='来源类型')),
                ('content_language', models.CharField(choices=[('zh', '中文'), ('ko', '韩文'), ('en', '英文'), ('el', '希腊文'), ('he', '希伯来文')], max_length=10, verbose_name='资料语言')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/', verbose_name='原始文件')),
                ('raw_text', models.TextField(blank=True, help_text='提取/转录后的全文', verbose_name='全文')),
                ('transcript_meta', models.JSONField(blank=True, default=dict, verbose_name='转录元数据')),
                ('tradition', models.CharField(blank=True, max_length=50, verbose_name='神学传统')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_annotation', '待标注'), ('annotated', '已标注'), ('in_review', '审核中'), ('approved', '已通过'), ('exported', '已导出')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_docs', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('target_models', models.ManyToManyField(blank=True, related_name='documents', to='corpus.aimodel', verbose_name='目标模型')),
                ('translation_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='corpus.translationgroup', verbose_name='翻译组')),
            ],
            options={
                'verbose_name': '资料',
                'verbose_name_plural': '资料',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verse_ref', models.CharField(max_length=100, verbose_name='经文引用')),
                ('verse_text', models.TextField(blank=True, verbose_name='经文')),
                ('commentary', models.TextField(verbose_name='注释')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='主题标签')),
                ('quality_score', models.FloatField(blank=True, null=True, verbose_name='质量评分')),
                ('disputed', models.BooleanField(default=False, verbose_name='争议内容')),
                ('auto_generated', models.BooleanField(default=False, verbose_name='AI自动生成')),
                ('ai_confidence', models.FloatField(blank=True, null=True, verbose_name='AI置信度')),
                ('needs_attention', models.BooleanField(default=False, verbose_name='需重点检查')),
                ('status', models.CharField(choices=[('pending_annotation', '待标注'), ('annotated', '已标注'), ('in_review', '审核中'), ('approved', '已通过'), ('rejected', '已打回')], default='pending_annotation', max_length=20, verbose_name='状态')),
                ('order', models.IntegerField(default=0, verbose_name='文档内顺序')),
                ('annotated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotated_entries', to=settings.AUTH_USER_MODEL, verbose_name='标注者')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='corpus.document', verbose_name='所属资料')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_entries', to=settings.AUTH_USER_MODEL, verbose_name='审核者')),
            ],
            options={
                'verbose_name': '条目',
                'verbose_name_plural': '条目',
                'ordering': ['document', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', '通过'), ('edit', '修改'), ('reject', '打回')], max_length=20, verbose_name='动作')),
                ('comment', models.TextField(blank=True, verbose_name='批注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='corpus.entry', verbose_name='条目')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审核者')),
            ],
            options={
                'verbose_name': '审核记录',
                'verbose_name_plural': '审核记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_claimable', models.BooleanField(default=True, verbose_name='可认领')),
                ('status', models.CharField(choices=[('open', '待处理'), ('claimed', '已认领'), ('done', '已完成')], default='open', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='指派给')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.document', verbose_name='资料')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aimodel',
            name='theologian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='corpus.theologian', verbose_name='神学家'),
        ),
    ]
